openapi: 3.0.3
info:
  description: VCDR Backend Public APIs.
  version: 1.0.0-oas3
  title: VCDR Backend Public APIs
  contact:
    name: VMware
  license:
    name: Copyright (c) 2021 VMware, Inc. All rights reserved.
  x-vmw-vapi-codegenconfig:
    package-name: com.vmware.vcdr
    tag-resources-by-url-path: true
security:
  - api_key: []
servers:
  - description: VCDR production backend
    url: https://vcdrsp-prd-vcdr-backend-res01-prd-us-west-2.vdp.vmware.com/api 
tags:
  - name: deployment-vcdr
    description: >-
      VCDR self-service APIs for Deployment (Deploy / Un-Deploy, Link with CSP
      etc.,)
paths:
  /vcdr/org/{org-id}/deployments:
    get:
      tags:
        - deployment-vcdr
      summary: Get all VCDR Deployments in given org
      description: Get all VCDR Deployments in given org
      operationId: getVcdrDeployments
      parameters:
        - $ref : '#/components/parameters/orgIdPathParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TenantDeployment'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    api_key:
      type: apiKey
      description: >-
        In order to make VMware Cloud Disaster Recovery REST API calls, you need
        to authenticate with the Cloud Services Platform, which will exchange an
        API token for an access token. This access token must be provided in the
        header for al VCDR REST API calls.<p>
      in: header
      name: csp-auth-token
  parameters:
    orgIdPathParam:
      name: org-id
      in: path
      description: organization identifier
      required: true
      schema:
        type: string
        format: uuid
    orgIdQueryParam:
      name: org-id
      in: query
      description: ORG identifier
      required: true
      schema:
        type: string
        example: 55f1a417-1c88-4bc0-aa38-5edb7ab6b47a
  schemas:
    TenantDeployment:
      title: Deployment info exposed to Tenant orgs
      type: object
      required:
        - id
        - type
        - state
        - spec
        - start_time
        - created_by
        - org_id
        - current_version
        - upgrade
        - release_type
        - lambda
      properties:
        id:
          type: string
          format: uuid
          description: Deployment ID
          example: b25fa423-1800-4ffb-b7cf-0ea4d0bd75b2
        type:
          $ref: '#/components/schemas/ServiceTypeEnum'
        state:
          $ref: '#/components/schemas/DeploymentStatesEnum'
        current_version:
          type: string
          description: Current version number of deployment
          minLength: 1
          example: 7.23.0.0
        upgrade:
          $ref: '#/components/schemas/DeploymentUpgradeStatusEnum'
        release_type:
          $ref: '#/components/schemas/ReleaseTypeEnum'
        lambda:
          $ref: '#/components/schemas/LambdaTypeEnum'
        lambda_migration_state:
          $ref: '#/components/schemas/LambdaMigrationStateEnum'
        spec:
          $ref: '#/components/schemas/TenantDeploymentSpec'
        start_time:
          description: Time at which Deployment started
          type: string
          format: date-time
          example: '2021-11-02T23:20:15Z'
        end_time:
          description: Time at which Deployment completed
          type: string
          format: date-time
          example: '2021-11-02T23:23:12Z'
        deletion_requested_time:
          nullable: true
          description: Time at which deployment deletion is requested.
          type: string
          format: date-time
          example: '2021-11-03T23:23:12Z'
        config:
          $ref: '#/components/schemas/TenantDeploymentConfig'
        created_by:
          type: string
          description: User who created the deployment.
          example: user1@acme.com
        deletion_requested_by:
          type: string
          nullable: true
          description: User who requested to delete deployment.
          example: user2@acme.com
        org_id:
          type: string
          description: Org id
          example: 1a2ef44d-ccb6-408d-bbbe-8e374a17afc1
    ServiceTypeEnum:
      title: Service Types
      type: string
      enum:
        - VCDR
        - VMCFS
      example: VCDR
    ReleaseTypeEnum:
      title: Release Types
      type: string
      default: GA
      enum:
        - GA
        - EA
      example: GA
    LambdaTypeEnum:
      title: Lambda type enum
      type: string
      enum:
        - COMMON
        - INDIVIDUAL
      example: COMMON
    LambdaMigrationStateEnum:
      title: Lambda migration state enum
      type: string
      enum:
        - NOT_STARTED
        - IN_PROGRESS
        - FAILED
        - COMPLETED
        - NOT_APPLICABLE
      example: NOT_STARTED
    TenantDeploymentSpec:
      title: Deployment specification in Tenant org
      type: object
      required:
        - provider
        - region
      properties:
        name:
          type: string
          description: Name of deployment
          maxLength: 127
          example: VCDR (us-west-2)
        provider:
          $ref: '#/components/schemas/CloudProvidersEnum'
        region:
          type: string
          description: Cloud Provider Region ID
          example: us-west-2
          minLength: 1
        seller_id:
          nullable: true
          type: string 
        seller:
          $ref: '#/components/schemas/SellerOfRecordEnum'
    TenantDeploymentConfig:
      title: Deployment configurations exposed to Tenant
      type: object
      properties:
        subscription_info:
          $ref: '#/components/schemas/SubscriptionConfig'
        cloud_provider: 
          $ref: '#/components/schemas/TenantCloudProviderConfig'
        orchestrator: 
          $ref: '#/components/schemas/TenantOrchestratorConfig'
    CloudProvidersEnum:
      title: Cloud Provider Types
      type: string
      enum:
        - AWS
        - MOCK
      example: AWS
    SellerOfRecordEnum:
      title: Seller Of Records
      type: string
      nullable: true
      enum:
        - VMWARE
        - AWS
        - INACTIVE_SELLER
      example: VMWARE
    SubscriptionConfig:
      title: Subscription config in Deployment
      type: object
      nullable: true
      properties:
        seller:
          nullable: true
          type: string 
        paid_pilot:
          type: boolean
          description: Whether Paid pilot was activated during deployment
          example: false
        term_subscription:
          type: boolean
          description: Whether TERM subscription is activated in given geo
          example: false
    TenantCloudProviderConfig:
      title: Cloud Provider config in Deployment exposed to Tenants
      type: object
      required:
        - provider
        - region
      nullable: true
      properties:
        provider:
          $ref: '#/components/schemas/CloudProvidersEnum'
        region:
          type: string
          description: Cloud Provider Region ID in which deployment was requested
          example: us-west-2
    TenantOrchestratorConfig:
      title: >-
        Deployment configuration for VCDR orchestrator (Control Shift / IRR)
        exposed to Tenants.
      type: object
      nullable: true
      properties:
        ip:
          type: string
          description: VCDR gateway IP.
          example: 72.34.122.1
        url:
          type: string
          description: VCDR gateway URL.
          example: https://foobar-1234.vcdr.vmware.com
    DeploymentStatesEnum:
      title: Deployment States
      type: string
      enum:
        - IN_PROGRESS
        - READY
        - FAILED
        - DELETION_REQUESTED
        - DELETING
        - DELETION_WAITING_APPROVAL
        - DELETION_FAILED
        - DELETED
      example: IN_PROGRESS
    DeploymentUpgradeStatusEnum:
      title: Deployment upgrade eligibility
      type: string
      enum:
        - ALLOWED
        - NOT_ALLOWED
        - ON_HOLD
      example: ALLOWED