openapi: 3.0.3
info:
  description: VCDR Backend Public APIs.
  version: '1.1' 
  title: VCDR Backend Public APIs
  contact:
    name: VMware
  license:
    name: Copyright (c) 2021 VMware, Inc. All rights reserved.
  x-vmw-vapi-codegenconfig:
    package-name: com.vmware.vcdr
    tag-resources-by-url-path: true
 
security:
  - api_key: []  

servers:
  - description: VCDR production backend
    url: 'https://vcdrsp-prd-vcdr-backend-res01-prd-us-west-2.vdp.vmware.com/api/vcdr' 
schemes:
  - https
tags:
  - name: vcdr-org
    description: 'CSP Org related APIs (Query VCDR tenant orgs, Service Instances etc.,)'
paths:
  /operator/deployments:
    get:
      tags:
        - vcdr-org
      summary: Get all Deployments
      description: Get all Deployments 
      parameters:
        - $ref: '#/components/parameters/orgIdQueryParam'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Deployment'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
   
          
  
components:
  securitySchemes:
    api_key:
      type: apiKey
      description: 'In order to make VMware Cloud Disaster Recovery REST API calls, you need to authenticate with the Cloud Services Platform, which will exchange an API token for an access token. This access token must be provided in the header for al VCDR REST API calls.<p>'
      in: header
      name: csp-auth-token
      
  parameters:
    orgIdPathParam:
      name: org-id
      in: path
      description: organization identifier
      required: true
      schema:
        type: string
        format: uuid

    orgIdQueryParam:
      name: org-id
      in: query
      description: ORG identifier
      required: false
      type: string 
      format: uuid
      example: "55f1a417-1c88-4bc0-aa38-5edb7ab6b47a"
      
  schemas:
    TenantOrchestratorConfig:
      title: >-
        Deployment configuration for VCDR orchestrator (Control Shift / IRR)
        exposed to Tenants.
      type: object
      properties:
        ip:
          type: string
          description: VCDR gateway IP.
          example: 72.34.122.1
        url:
          type: string
          description: VCDR gateway URL.
          example: https://foobar-1234.vcdr.vmware.com
    TenantCloudProviderConfig:
      title: Cloud Provider config in Deployment exposed to Tenants
      type: object
      required:
        - provider
        - region
      properties:
        provider:
          $ref: '#/components/schemas/CloudProvidersEnum'
        region:
          type: string
          nullable: true
          description: Cloud Provider Region ID in which deployment was requested
          example: us-west-2
    TenantDeploymentConfig:
      title: Deployment configurations exposed to Tenant
      type: object
      properties:
        subscription_info:
          $ref: '#/components/schemas/SubscriptionConfig'
        cloud_provider:
          $ref: '#/components/schemas/TenantCloudProviderConfig'
        orchestrator:
          $ref: '#/components/schemas/TenantOrchestratorConfig'
    TenantDeploymentSpec:
      title: Deployment specification in Tenant org
      type: object
      required:
        - type
        - provider
        - region
      properties:
        name:
          type: string
          description: Name of deployment
          maxLength: 127
          example: VCDR (us-west-2)
        type:
          $ref: '#/components/schemas/DeploymentTypesEnum'
        provider:
          $ref: '#/components/schemas/CloudProvidersEnum'
        region:
          type: string
          nullable: true
          description: Cloud Provider Region ID
          example: us-west-2
        seller:
          $ref: '#/components/schemas/SellerOfRecordEnum'
  
    DeploymentTypesEnum:
      title: Deployment Types
      type: string
      enum:
        - VCDR
      example: VCDR
    CloudProvidersEnum:
      title: Cloud Provider Types
      type: string
      enum:
        - AWS
        - MOCK
      example: AWS
    SellerOfRecordEnum:
      title: Seller Of Records
      type: string
      enum:
        - VMWARE
        - AWS
        - INACTIVE_SELLER
      example: VMWARE
    SubscriptionConfig:
      title: Subscription config in Deployment
      type: object
      properties:
        paid_pilot:
          type: boolean
          nullable: true
          description: Whether Paid pilot was activated during deployment
          example: false
        term_subscription:
          type: boolean
          nullable: true
          description: Whether TERM subscription is activated in given geo
          example: false
    DeploymentStatesEnum:
      title: Deployment States
      type: string
      enum:
        - IN_PROGRESS
        - READY
        - FAILED
        - DELETION_REQUESTED
        - DELETING
        - DELETION_WAITING_APPROVAL
        - DELETION_FAILED
        - DELETED
      example: IN_PROGRESS
    TenantDeployment:
      title: Deployment info exposed to Tenant orgs
      type: object
      required:
        - id
        - type
        - state
        - spec
        - start_time
        - created_by
        - org_id
      properties: 
        id:
          type: string
          format: uuid
          description: Deployment ID
          example: b25fa423-1800-4ffb-b7cf-0ea4d0bd75b2
        type:
          $ref: '#/components/schemas/DeploymentTypesEnum'
        state:
          $ref: '#/components/schemas/DeploymentStatesEnum'
        spec:
          $ref: '#/components/schemas/TenantDeploymentSpec'
        start_time:
          description: Time at which Deployment started
          type: string
          format: 'date-time'
          example: "2021-11-02T23:20:15Z"
        end_time:
          description: Time at which Deployment completed
          type: string
          format: 'date-time'
          example: "2021-11-02T23:23:12Z"
          nullable: true
        deletion_requested_time:
          description: Time at which deployment deletion is requested.
          type: string
          format: 'date-time'
          example: "2021-11-03T23:23:12Z"
          nullable: true
        config:
          $ref: '#/components/schemas/TenantDeploymentConfig'
        created_by:
          type: string
          description: User who created the deployment.
          example: "user1@acme.com"
        deletion_requested_by:
          type: string
          description: User who requested to delete deployment.
          example: "user2@acme.com"
          nullable: true
        org_id:
          type: string
          description: Org id
          example: 1a2ef44d-ccb6-408d-bbbe-8e374a17afc1

    Deployment:
      title: Deployment
      type: object
      required:
        - id
        - type
        - state
        - spec
        - start_time
        - created_by
        - org_id
      properties:
        id:
          type: string
          format: uuid
          description: Deployment ID
          example: b25fa423-1800-4ffb-b7cf-0ea4d0bd75b2
        type:
          $ref: '#/components/schemas/DeploymentTypesEnum'
        state:
          $ref: '#/components/schemas/DeploymentStatesEnum'
        spec:
          $ref: '#/components/schemas/DeploymentSpec'
        start_time:
          description: Time at which Deployment started
          type: string
          format: 'date-time'
          example: "2021-11-02T23:20:15Z"
        end_time:
          description: Time at which Deployment completed
          type: string
          format: 'date-time'
          example: "2021-11-02T23:23:12Z"
        deletion_requested_time:
          description: Time at which deployment deletion is requested.
          type: string
          format: 'date-time'
          example: "2021-11-03T23:23:12Z"
        deletion_approved_time:
          description: Time at which deployment delete request is approved.
          type: string
          format: 'date-time'
          example: "2021-11-04T03:21:17Z"
        config:
          $ref: '#/components/schemas/DeploymentConfig'
        created_by:
          type: string
          description: User who created the deployment.
          example: "user1@acme.com"
        deletion_requested_by:
          type: string
          description: User who requested to delete deployment.
          example: "user2@acme.com"
        deletion_approved_by:
          type: string
          description: User who approved the deployment delete request.
          example: "admin@vmware.com"
        org_id:
          type: string
          description: Org id
          example: 1a2ef44d-ccb6-408d-bbbe-8e374a17afc1
    DeploymentSpec:
      title: Deployment specification
      type: object
      required:
        - org_id
        - name
        - type
        - provider
        - region
      properties:
        org_id:
          type: string
          description: Org id
          example: 1a2ef44d-ccb6-408d-bbbe-8e374a17afc1
        name:
          type: string
          description: Name of deployment
          maxLength: 127
          example: VCDR (us-west-2)
        type:
          $ref: '#/components/schemas/DeploymentTypesEnum'
        provider:
          $ref: '#/components/schemas/CloudProvidersEnum'
        region:
          type: string
          description: Cloud Provider Region ID
          example: us-west-2
        availability_zone:
          type: string
          description: Availability Zone ID in given Region
          example: usw2-az4
        generate_dns_entry:
          type: boolean
          description: Generate DNS entry for deployment (Default - true)
          example: false
        create_service_instance:
          type: boolean
          description: Create Service Instance and OAuth apps for VCDR (Default - true)
          example: false
        link_csp_tile:
          type: boolean
          description: Link CSP Tile after Service Instance is created (Default - true)
          example: false
     
    DeploymentConfig:
      title: Deployment configurations exposed to Operator.
      type: object
      properties:
        subscription_info:
          $ref: '#/components/schemas/SubscriptionConfig'
        initial_deployment_images:
          type: object
          description: Initial images used for deployment
          additionalProperties: true
        cloud_provider:
          $ref: '#/components/schemas/CloudProviderConfig'
        orchestrator:
          $ref: '#/components/schemas/OrchestratorConfig'
        installDb:
          $ref: '#/components/schemas/InstallDbConfig'
        migrationInfo:
          $ref: '#/components/schemas/DeploymentMigrationInfo'
        upgrade_deployment_info:
          $ref: '#/components/schemas/UpgradeDeploymentInfo'

    CloudProviderConfig:
      title: Cloud Provider config in Deployment
      type: object
      required:
        - provider
        - region
      properties:  
        provider:
          $ref: '#/components/schemas/CloudProvidersEnum'
        region:
          type: string
          description: Cloud Provider Region ID in which deployment was requested
          example: us-west-2
        availability_zone:
          type: string
          description: Availability Zone ID in given Region (randomized if user did not choose)
          example: usw2-az4
        account_id:
          type: string
          description: AWS account ID (if AWS provider)
          example: 123456789012

    OrchestratorConfig:
      title: Deployment configuration for VCDR orchestrator (Control Shift / IRR).
      type: object
      required: # TODO do we make any of these required ?
        #- ip
      properties:
        uuid:
          type: string
          description: VCDR gateway UUID (IRR instance)
          example: 12458867-79e8-4a82-9d39-bfd0f2694098
        ip:
          type: string
          description: VCDR gateway IP.
          example: 72.34.122.1
        url:
          type: string
          description: VCDR gateway URL.
          example: https://foobar-1234.vcdr.vmware.com
        support_url:
          type: string
          description: VCDR gateway URL (for support to login)
          example: https://foobar-1234.vcdr.vmware.com/?orgLink=/csp/gateway/am/api/orgs/<service/operator org uuid>

    InstallDbConfig:
      title: InstallDb Config in Deployment
      type: object
      properties:
        activated:
          type: boolean
          description: Flag to indicate whether Install Case has been created successfully during Activation

    DeploymentMigrationInfo:
      title: Deployment Migration Info
      type: object
      properties:
        migrated:
          type: boolean
          example: true
          description: Flag to indicate whether the given deployment was migrated after legacy VCDR deployment
        migrated_by:
          type: string
          example: operator@vmware.com
          description: Operator User who triggered the migration
        migrated_date:
          type: string
          format: 'date-time'
          example: "2022-02-02T02:02:02.022Z"
    UpgradeDeploymentInfo:
      title: Details of history of upgrades for a deployments for a Service in SaaS Infra
      type: object
      required:
        - last_upgrade
        - upgrade_history
      properties:
        last_upgrade:
          $ref: '#/components/schemas/LastUpgrade'
        upgrade_history:
          type: array
          items:
            $ref: '#/components/schemas/UpgradeInfo'
    UpgradeInfo: #TODO  Make it service specific(Interface).
      title: Upgrade Deployment Information containing details of release components used for upgrade
      type: object
      required:
        - status
        - version
        - upgraded_by
        - irr_ami_name
        - cdvx_ami_name
        - lambda_zip_file_name
      properties:
        status:
          $ref: '#/components/schemas/UpgradeDeploymentStatusEnum'
        version:
          type: string
        upgraded_by:
          type: string
          description: User who upgraded the deployment.
          example: "user1@acme.com"
        irr_ami_name:
          type: string
          example: Datrium-IRR-V1-7.21.6.0-42482_b7eb14b_g
        irr_ami_id:
          type: string
          example: ami-0d84cb2d46ae83190
        cdvx_ami_name:
          type: string
          example: Datrium-IRR-V1-7.21.6.0-42482_b7eb14b_g
        cdvx_ami_id:
          type: string
          example: ami-0d84cb2d46ae83191
        lambda_zip_file_name:
          type: string
          example: "da-svcmgmt-lambda-7.21.10.0-43634_c12405e.zip"
        deployed_date:
          type: string
          description: Creation/Trigger date for the Deployment
          format: 'date-time'
          example: "2021-11-02T23:19:59Z"
    UpgradeDeploymentStatusEnum:
      title: Enums defining various upgrades statuses.
      type: string
      enum:
        - DEPLOYMENT_UPGRADE_FAILED
        - DEPLOYMENT_UPGRADE_TRIGGERED
        - DEPLOYMENT_UPGRADE_IN_PROGRESS
        - DEPLOYMENT_UPGRADE_SUCCESSFUL
        - DEPLOYMENT_VERSION_NOT_AVAILABLE
        - DEPLOYMENT_UPGRADE_CHECK_FAILED
        - DEPLOYMENT_UPGRADE_CHECK_PASSED
        - DEPLOYMENT_UPGRADE_PATHS_FOUND
        - DEPLOYMENT_UPGRADE_DONE_MANUALLY
        - DEPLOYMENT_NON_DEFAULT_UPGRADE_USE_FORCE
        - DEPLOYMENT_NOT_IN_READY_STATE
        - DEPLOYMENT_DOES_NOT_EXIST
        - DEPLOYMENT_UPGRADE_CURRENT_VERSION_MISMATCH
        - DEPLOYMENT_UPGRADE_CURRENT_VERSION_DEFAULT
        - DEPLOYMENT_UPGRADE_NO_DEPLOYMENT_INFO_FOUND
        - DEPLOYMENT_UPGRADE_NO_UPGRADE_INFO_FOUND
        - DEPLOYMENT_UPGRADE_NO_UPGRADE_TRIGGERED
        - DEPLOYMENT_UPGRADE_ALREADY_IN_TRIGGERED_STATE
        - DEPLOYMENT_UPGRADE_ALREADY_AT_TARGET_VERSION
        - DEPLOYMENT_UPGRADE_EC2_INSTANCES_FOUND
        - DEPLOYMENT_UPGRADE_NO_EC2_INSTANCES_FOUND
        - DEPLOYMENT_UPGRADE_PATHS_NOT_FOUND
        - DEPLOYMENT_UPGRADE_INITIAL_FIRST_INSTALL
        - DEPLOYMENT_UPGRADE_INSTANCES_AT_MIXED_VERSION
        - DEPLOYMENT_UPGRADE_FAILED_TO_FIND_TARGET_VERSION
        - DEPLOYMENT_UPGRADE_NON_DEFAULT_SPECIFY_TARGET_VERSION_AND_FORCE
        - DEPLOYMENT_UPGRADE_MULTIPLE_OPTIONS_SPECIFY_VERSION_AND_FORCE
    LastUpgrade:
      title: Last or Most Recent upgrade details of a deployment
      type: object
      required:
        - from_version
        - to_version
        - to_upgrade_info
        - created_at
      properties:
        from_version:
          type: string
        to_version:
          type: string
        to_upgrade_info:
          description: Details of the Target Version upgraded to.
          $ref: '#/components/schemas/UpgradeInfo'
        created_at:
          type: string
          description:  Time for the upgrade last operation, triggerred or status update
          format: 'date-time'
          example: "2021-11-02T23:19:59Z"
